import { useMemo, useState, type FormEvent } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import { aceitarConvitePrimeiroAcesso } from "../../services/empresa/companyInvite.service";
import { BrandConfig } from "../../config/brand";
export default function FirstAccessPage() {
  const [searchParams] = useSearchParams(); const navigate = useNavigate(); const token = useMemo(() => searchParams.get("token") || "", [searchParams]); const [nome, setNome] = useState(""); const [email, setEmail] = useState(""); const [senha, setSenha] = useState(""); const [confirmacao, setConfirmacao] = useState(""); const [erro, setErro] = useState(""); const [enviando, setEnviando] = useState(false);
  async function concluir(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setErro(""); if (!token) return setErro("Este link de primeiro acesso esta incompleto."); if (senha !== confirmacao) return setErro("As senhas nao conferem."); setEnviando(true); const { data, error } = await aceitarConvitePrimeiroAcesso({ token, nome, email, senha }); setEnviando(false); if (error || !data) return setErro(error?.message || "Nao foi possivel criar o acesso."); navigate(`/pdv/${data.empresaSlug}`, { replace: true }); }
  return <main className="min-h-screen bg-slate-100 px-4 py-10 text-slate-900"><section className="mx-auto max-w-lg rounded-2xl bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-bold uppercase tracking-wide text-green-700">{BrandConfig.platformName}</p><h1 className="mt-2 text-2xl font-black">Primeiro acesso da empresa</h1><p className="mt-2 text-sm leading-6 text-slate-600">Crie o administrador principal para acessar o ERP da sua empresa.</p>{!token ? <p className="mt-6 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">Link de convite invalido.</p> : <form className="mt-6 space-y-4" onSubmit={concluir}><label className="block text-sm font-bold">Nome<input required value={nome} onChange={(event) => setNome(event.target.value)} className="mt-1 w-full rounded-xl border px-4 py-3" /></label><label className="block text-sm font-bold">E-mail<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded-xl border px-4 py-3" /></label><label className="block text-sm font-bold">Senha<input required minLength={8} type="password" value={senha} onChange={(event) => setSenha(event.target.value)} className="mt-1 w-full rounded-xl border px-4 py-3" /></label><label className="block text-sm font-bold">Confirmar senha<input required minLength={8} type="password" value={confirmacao} onChange={(event) => setConfirmacao(event.target.value)} className="mt-1 w-full rounded-xl border px-4 py-3" /></label>{erro && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{erro}</p>}<button disabled={enviando} className="w-full rounded-xl bg-green-700 px-4 py-3 font-bold text-white disabled:opacity-50">{enviando ? "Criando acesso..." : "Criar administrador"}</button></form>}</section></main>;
}
