-- Sprint 162 - ERP/PDV: trocas, devolucoes e vale-troca.
-- Escopo: fluxo operacional integrado a estoque, caixa e historico de vendas. Sem fiscal/financeiro.

alter table public.erp_pdv_vendas
  add column if not exists vale_troca_id uuid,
  add column if not exists vale_troca_valor_utilizado numeric(12, 2) not null default 0,
  add column if not exists pagamento_complementar numeric(12, 2) not null default 0,
  add column if not exists historico_operacional jsonb not null default '[]'::jsonb;

alter table public.erp_pdv_venda_itens
  add column if not exists quantidade_devolvida numeric(12, 3) not null default 0;

create table if not exists public.erp_pdv_vale_trocas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  venda_origem_id uuid references public.erp_pdv_vendas(id) on delete set null,
  cliente_id uuid references public.erp_pdv_clientes(id) on delete set null,
  numero bigint generated by default as identity,
  cliente_nome text not null default '',
  valor_original numeric(12, 2) not null default 0,
  saldo_restante numeric(12, 2) not null default 0,
  emitido_em timestamptz not null default now(),
  validade_em date not null,
  status text not null default 'ativo' check (status in ('ativo', 'utilizado', 'expirado', 'cancelado')),
  observacao text not null default '',
  historico jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_pdv_devolucoes (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  venda_id uuid not null references public.erp_pdv_vendas(id) on delete cascade,
  vale_troca_id uuid references public.erp_pdv_vale_trocas(id) on delete set null,
  numero bigint generated by default as identity,
  tipo text not null default 'parcial' check (tipo in ('total', 'parcial')),
  motivo text not null,
  operador text not null default '',
  cliente_nome text not null default '',
  valor_devolvido numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.erp_pdv_devolucao_itens (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  devolucao_id uuid not null references public.erp_pdv_devolucoes(id) on delete cascade,
  venda_item_id uuid not null references public.erp_pdv_venda_itens(id) on delete cascade,
  produto_id uuid references public.erp_pdv_produtos(id) on delete set null,
  descricao text not null,
  quantidade numeric(12, 3) not null default 0,
  preco_unitario numeric(12, 2) not null default 0,
  valor_total numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.erp_pdv_vale_troca_movimentacoes (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  vale_troca_id uuid not null references public.erp_pdv_vale_trocas(id) on delete cascade,
  venda_id uuid references public.erp_pdv_vendas(id) on delete set null,
  devolucao_id uuid references public.erp_pdv_devolucoes(id) on delete set null,
  tipo text not null check (tipo in ('emissao', 'utilizacao', 'cancelamento')),
  valor numeric(12, 2) not null default 0,
  saldo_antes numeric(12, 2) not null default 0,
  saldo_depois numeric(12, 2) not null default 0,
  observacao text not null default '',
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'erp_pdv_vendas_vale_troca_id_fkey'
  ) then
    alter table public.erp_pdv_vendas
      add constraint erp_pdv_vendas_vale_troca_id_fkey
      foreign key (vale_troca_id) references public.erp_pdv_vale_trocas(id) on delete set null;
  end if;
end $$;

create index if not exists erp_pdv_vendas_empresa_numero_idx
  on public.erp_pdv_vendas (empresa_id, numero);

create index if not exists erp_pdv_devolucoes_empresa_created_idx
  on public.erp_pdv_devolucoes (empresa_id, created_at desc);

create index if not exists erp_pdv_devolucoes_empresa_venda_idx
  on public.erp_pdv_devolucoes (empresa_id, venda_id);

create index if not exists erp_pdv_vale_trocas_empresa_status_idx
  on public.erp_pdv_vale_trocas (empresa_id, status, created_at desc);

create index if not exists erp_pdv_vale_troca_movimentacoes_empresa_vale_idx
  on public.erp_pdv_vale_troca_movimentacoes (empresa_id, vale_troca_id, created_at desc);

alter table public.erp_pdv_devolucoes enable row level security;
alter table public.erp_pdv_devolucao_itens enable row level security;
alter table public.erp_pdv_vale_trocas enable row level security;
alter table public.erp_pdv_vale_troca_movimentacoes enable row level security;

do $$
declare
  tabela text;
  politica text;
begin
  foreach tabela in array array[
    'erp_pdv_devolucoes',
    'erp_pdv_devolucao_itens',
    'erp_pdv_vale_trocas',
    'erp_pdv_vale_troca_movimentacoes'
  ]
  loop
    politica := 'Permitir acesso operacional ' || tabela;

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = tabela
        and policyname = politica
    ) then
      execute format(
        'create policy %I on public.%I for all to anon, authenticated using (true) with check (true)',
        politica,
        tabela
      );
    end if;
  end loop;
end $$;

notify pgrst, 'reload schema';
