-- Migration: create initial ERP/PDV structure for MikaON.
-- Scope: base online ERP/PDV for the Mikatech pilot. No fiscal or offline mode.

create table if not exists public.erp_pdv_categorias (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  nome text not null,
  descricao text not null default '',
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_pdv_produtos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  categoria_id uuid references public.erp_pdv_categorias(id) on delete set null,
  nome text not null,
  codigo_barras text not null default '',
  sku text not null default '',
  custo numeric(12, 2) not null default 0,
  preco_venda numeric(12, 2) not null default 0,
  unidade text not null default 'un',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_pdv_estoques (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  produto_id uuid not null references public.erp_pdv_produtos(id) on delete cascade,
  quantidade_atual numeric(12, 3) not null default 0,
  estoque_minimo numeric(12, 3) not null default 0,
  updated_at timestamptz not null default now(),
  constraint erp_pdv_estoques_produto_unique unique (produto_id)
);

create table if not exists public.erp_pdv_movimentacoes (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  produto_id uuid not null references public.erp_pdv_produtos(id) on delete cascade,
  tipo text not null check (tipo in ('entrada', 'saida', 'ajuste', 'venda')),
  quantidade numeric(12, 3) not null,
  estoque_anterior numeric(12, 3) not null default 0,
  estoque_posterior numeric(12, 3) not null default 0,
  origem text not null default 'manual',
  observacao text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.erp_pdv_caixas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  status text not null default 'fechado' check (status in ('aberto', 'fechado')),
  aberto_em timestamptz,
  fechado_em timestamptz,
  saldo_inicial numeric(12, 2) not null default 0,
  saldo_final numeric(12, 2) not null default 0,
  observacao text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_pdv_vendas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  caixa_id uuid references public.erp_pdv_caixas(id) on delete set null,
  numero bigint generated by default as identity,
  status text not null default 'rascunho' check (status in ('rascunho', 'finalizada', 'cancelada')),
  subtotal numeric(12, 2) not null default 0,
  desconto numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  forma_pagamento text not null default '',
  cliente_nome text not null default '',
  observacao text not null default '',
  finalizada_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.erp_pdv_venda_itens (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  venda_id uuid not null references public.erp_pdv_vendas(id) on delete cascade,
  produto_id uuid references public.erp_pdv_produtos(id) on delete set null,
  descricao text not null,
  quantidade numeric(12, 3) not null default 1,
  preco_unitario numeric(12, 2) not null default 0,
  desconto numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists erp_pdv_categorias_empresa_idx
  on public.erp_pdv_categorias (empresa_id, ordem, nome);

create index if not exists erp_pdv_produtos_empresa_nome_idx
  on public.erp_pdv_produtos (empresa_id, nome);

create index if not exists erp_pdv_produtos_empresa_sku_idx
  on public.erp_pdv_produtos (empresa_id, sku);

create index if not exists erp_pdv_produtos_empresa_codigo_barras_idx
  on public.erp_pdv_produtos (empresa_id, codigo_barras);

create unique index if not exists erp_pdv_produtos_empresa_sku_unique_idx
  on public.erp_pdv_produtos (empresa_id, sku)
  where sku <> '';

create unique index if not exists erp_pdv_produtos_empresa_codigo_barras_unique_idx
  on public.erp_pdv_produtos (empresa_id, codigo_barras)
  where codigo_barras <> '';

create index if not exists erp_pdv_estoques_empresa_produto_idx
  on public.erp_pdv_estoques (empresa_id, produto_id);

create index if not exists erp_pdv_movimentacoes_empresa_produto_idx
  on public.erp_pdv_movimentacoes (empresa_id, produto_id, created_at desc);

create index if not exists erp_pdv_vendas_empresa_created_idx
  on public.erp_pdv_vendas (empresa_id, created_at desc);

create index if not exists erp_pdv_venda_itens_empresa_venda_idx
  on public.erp_pdv_venda_itens (empresa_id, venda_id);

alter table public.erp_pdv_categorias enable row level security;
alter table public.erp_pdv_produtos enable row level security;
alter table public.erp_pdv_estoques enable row level security;
alter table public.erp_pdv_movimentacoes enable row level security;
alter table public.erp_pdv_caixas enable row level security;
alter table public.erp_pdv_vendas enable row level security;
alter table public.erp_pdv_venda_itens enable row level security;

do $$
declare
  tabela text;
  politica text;
begin
  foreach tabela in array array[
    'erp_pdv_categorias',
    'erp_pdv_produtos',
    'erp_pdv_estoques',
    'erp_pdv_movimentacoes',
    'erp_pdv_caixas',
    'erp_pdv_vendas',
    'erp_pdv_venda_itens'
  ]
  loop
    politica := 'Permitir acesso operacional ' || tabela;

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = tabela
        and policyname = politica
    ) then
      execute format(
        'create policy %I on public.%I for all to anon, authenticated using (true) with check (true)',
        politica,
        tabela
      );
    end if;
  end loop;
end $$;

update public.empresas
set recursos_contratados =
  coalesce(recursos_contratados, '{}'::jsonb) || jsonb_build_object('erp_pdv', true)
where slug = 'mikatech';

notify pgrst, 'reload schema';
